### PR TITLE
Rejects when the submitted block and the pending deposits queue are both empty

### LINKED ISSUE #1206: Do not process empty blocks without pending deposits in the CAPE contract
See #1203 and this [discussion](https://espresso.zulipchat.com/#narrow/stream/311688-CAPE/topic/Future.20of.20CAPE/near/292042846) for context.

### PR DESCRIPTION
**Pull request by philippecamacho**
Closes #1206

### CODE REVIEW

**Comment by sveitser** [comment]
LGTM but I wonder why not checking if there are no commitments instead of checking if there no pending deposits and no notes? It seems a bit simpler to me and since commitments are what go into the merkle tree I think it easier to understand why we reject the block.

In any event I think it would be good to add a comment somewhere about why we reject the block and what problem is caused by not doing that.

**Review by sveitser — CHANGES_REQUESTED** [review]
I think we should add a comment as to why we reject empty blocks.

**Comment by philippecamacho** [comment]
> LGTM but I wonder why don't we check if there are no commitments instead of checking if there no pending deposits and no notes? It seems a bit simpler to me and since commitments are what go into the merkle tree I think it easier to understand why we reject the block.
> 
Yes, I agree. On the other side it seems to save a bit of gas to reject the block right away. WDYT?

> In any event I think it would be good to add a comment somewhere about why we reject the block and what problem is caused by not doing that.

Yes, added in e963fc1

**Comment by philippecamacho** [comment]
> I think we should add a comment as to why we reject empty blocks.

Yes, added in e963fc1.

**Review by sveitser — APPROVED** [review]
LGTM

**Pull request merged**
