### PR TITLE
Arbitrum goerli preparations

### LINKED ISSUE #1238: Deploy tokens

### PR DESCRIPTION
**Pull request by sveitser**
Close #1238.

I also think this are all the changes needed in this repo to update the wallet docker image for #1237  (cc @Ancient123)
edit: I forgot about the official asset library, added that to #1237.

If this is okay I will deploy the tokens and commit the deployment artifacts.

### CODE REVIEW

**Review by Ancient123 — APPROVED** [review]

**Comment by Ancient123** [comment]
Looks like the wallet changes that are/were needed.

**Comment by sveitser** [comment]
@philippecamacho I'm not quite sure why the test is flaky. It works fine at the beginning but starts failing after geth is running for a while. :shrug:

**Review by philippecamacho — APPROVED** [review]
LGTM

**Comment by sveitser** [comment]
@philippecamacho @sveitser @jbearer 

I deployed the token contracts to arbitrum goerli and added an updated official asset library toml. I think @Ancient123 needs to run the `gen-official-asset-library` binary to generate the `.lib` file.

**Pull request merged**
