### PR TITLE
Run CAPE demo locally

### LINKED ISSUE #540: Fully functional CAPE demo running locally (minus GUI)
We should have a script (or similar) that takes care of everything to run a local environment with the complete demo functionality.

The script needs to:

- Start a geth node
- Deploy contracts
- Start all necessary services: EQS, relayer, wallet
- Configure the CLI to work with the local deployment

### PR DESCRIPTION
**Pull request by sveitser**
- Adds a script to run the demo locally.
- The changes to rust code are to standardize and disambiguate the env var names.
- [x] Add faucet service after #749 is merged.

Close #540

### CODE REVIEW

**Review by jbearer — APPROVED** [review]

**Comment by philippecamacho** [comment]
When I run "cape-demo" I get the following:

> [nix-shell:~/repositories/Translucence/cape]$ cape-demo
>    Compiling address_book v0.0.2 (/home/philippe/repositories/Translucence/cape/address_book)
>    Compiling cap-rust-sandbox v0.2.0 (/home/philippe/repositories/Translucence/cape/contracts/rust)
>    Compiling relayer v0.2.0 (/home/philippe/repositories/Translucence/cape/relayer)
>    Compiling eqs v0.0.2 (/home/philippe/repositories/Translucence/cape/eqs)
>    Compiling cape-workflow v0.2.0 (/home/philippe/repositories/Translucence/cape/doc/workflow)
>    Compiling cape_wallet v0.2.0 (/home/philippe/repositories/Translucence/cape/wallet)
>    Compiling faucet v0.1.0 (/home/philippe/repositories/Translucence/cape/faucet)
>     Finished release [optimized] target(s) in 1m 18s
> Unpacking universal parameters... done in 10170 ms
> Using keystore dir /run/user/1000/cap-ethereum-data-OcTPynLN
> Waiting for port 8545 ...
> Importing private key ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
> Waiting for port 8545 ...
> Address: {f39fd6e51aad88f6f4ce6ab8827279cfffb92266}
> Importing private key 59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
> Waiting for port 8545 ...
> Address: {70997970c51812dc3a010c7d01b50e0d17dc79c8}
> Initializing geth with genesis file
> INFO [03-21|12:23:40.337] Maximum peer count                       ETH=50 LES=0 total=50
> INFO [03-21|12:23:40.338] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
> INFO [03-21|12:23:40.338] Set global gas cap                       cap=50,000,000
> INFO [03-21|12:23:40.814] Using developer account                  address=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
> INFO [03-21|12:23:40.814] Allocated cache and file handles         database=/run/user/1000/cap-ethereum-data-OcTPynLN/geth/chaindata cache=512.00MiB handles=524,288
> INFO [03-21|12:23:40.815] Opened ancient database                  database=/run/user/1000/cap-ethereum-data-OcTPynLN/geth/chaindata/ancient readonly=false
> INFO [03-21|12:23:40.815] Freezer shutting down 
> INFO [03-21|12:23:40.815] Allocated cache and file handles         database=/run/user/1000/cap-ethereum-data-OcTPynLN/geth/chaindata cache=16.00MiB  handles=16
> INFO [03-21|12:23:40.815] Writing custom genesis block 
> INFO [03-21|12:23:40.816] Persisted trie from memory database      nodes=3 size=455.00B time="31.601µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
> INFO [03-21|12:23:40.816] Successfully wrote genesis state         database=chaindata hash=7ab0d5..a2971a
> INFO [03-21|12:23:40.816] Allocated cache and file handles         database=/run/user/1000/cap-ethereum-data-OcTPynLN/geth/lightchaindata cache=16.00MiB  handles=16
> INFO [03-21|12:23:40.816] Writing custom genesis block 
> INFO [03-21|12:23:40.816] Persisted trie from memory database      nodes=3 size=455.00B time="12.37µs"  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
> INFO [03-21|12:23:40.816] Successfully wrote genesis state         database=lightchaindata hash=7ab0d5..a2971a
> Starting geth node ...
> Waiting for port 8545 ...
> Nothing to compile
> No need to generate any newer typings.
> deploying "RescueLib" (tx: 0x15978c27e6287e92853a88001451043aa3deba8eb55febecf30ca08feeb48d20)...: deployed at 0x5FbDB2315678afecb367f032d93F642f64180aa3 with 2016540 gas
> deploying "VerifyingKeys" (tx: 0x264d109a6e52f2b8c04b5c2f1f6e0120ee0981b605641d08e363375baedccf32)...: deployed at 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512 with 2288609 gas
> deploying "PlonkVerifier" (tx: 0x58ab57029802e8a7cecf0b5f4169cd036e1cb24158f89b4322667d5d1344c203)...: deployed at 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0 with 3296846 gas
> Using CAPE_FAUCET_MANAGER_ENC_KEY=0x6f73fe678d517e4f70c700cf814bf23053415924becb8b250f6510299c359f68
> Using CAPE_FAUCET_MANAGER_ADDRESS_X=0x0c9904a1a74583ac0ea2de3c9db9813fe9c496a56ff1b85045cc383c1918ea65
> Using CAPE_FAUCET_MANAGER_ADDRESS_Y=0x2779916e8658e96924714d30bfa2631b33d6f4ae156d0fd4f8af722daeecbed6
> deploying "CAPE" (tx: 0x0ceb2abc3945652ded2227c6e6ec15d909791dd8455d59e548db1ce44dae8250)...: deployed at 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9 with 7413790 gas
> executing CAPE.faucetSetupForTestnet (tx: 0x50f45112d373ae575b4d2db13d8f88ddf251939e32004c40a79e458e85a4e5dd) ...: performed with 3607003 gas
> deploying "SimpleToken" (tx: 0x3da41be8c741ad25676cce80dd33ec93fb3a9c13226ddca8ec340c92af9b519f)...: deployed at 0x5FC8d32690cc91D4c39d9d3abcBD16989F875707 with 635803 gas
> Waiting for port 50000 ...
> wallet-api   | Running...
> eqs          | Running...
> address-book | Running...
> faucet       | Running...
> relayer      | Running...
> wallet-api   | /nix/store/4nmqxajzaf60yjribkgvj5j54x9yvr1r-bash-5.1-p12/bin/bash: line 1: target/release/web_server: No such file or directory
> wallet-api   | exit status 127
> relayer      | Interrupting...
> eqs          | Interrupting...
> address-book | Interrupting...
> eqs          | signal: interrupt
> address-book | signal: interrupt
> relayer      | signal: interrupt
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> faucet       | Killing...
> Waiting for port 50000 ...
> faucet       | signal: killed
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> Waiting for port 50000 ...
> 

Looks like something is wrong, in particular because of this message: `"wallet-api | /nix/store/4nmqxajzaf60yjribkgvj5j54x9yvr1r-bash-5.1-p12/bin/bash: line 1: target/release/web_server: No such file or directory"`

**Comment by sveitser** [comment]
Ah yes the procfile is still using the old name of the executable. Will fix.

**Comment by philippecamacho** [comment]
> Is this on the latest commit?

I think so:
```
[nix-shell:~/repositories/Translucence/cape]$ git log -1 
commit 871a084a1ae6f3818adab1c0ffb51690bd59ba3b (HEAD -> feat/t540-local-cape-demo, origin/feat/t540-local-cape-demo)
Author: sveitser <sveitser@gmail.com>
Date:   Fri Mar 18 17:51:10 2022 +0100

    Quote env vars when showing config
    
    - Run renamed faucet setup binary.


```

**Comment by sveitser** [comment]
@philippecamacho you can try again. Not that at the end, after printing the configuration it currently shows this error

```
faucet       | error saving received records: BadMerkleProof
```

**Comment by philippecamacho** [comment]
> @philippecamacho you can try again. Note that at the end, after printing the configuration it currently shows this error
> 
> ```
> faucet       | error saving received records: BadMerkleProof
> ```
I confirm I get this error message. But this is expected right?

**Comment by jbearer** [comment]
I think the problem is that the wallet is being created with the mock backend (`faucet_wallet_test_setup`) and then instantiated with the real backend (`faucet`). I think I can fix this pretty easily. @sveitser is it cool if I push to this branch?

**Comment by sveitser** [comment]
@jbearer yes please!

**Pull request merged**
